pipeline {
    agent any
    tools {
        maven "3.6.3"
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout started...'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/dhnnjy11/spring-boot-test-app.git']]])
            } 
        }
    }
}
